name: niryo_ned
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - tensorflow==2.9.1
  - pillow
  - opencv
  - cmake  
  - numpy<2.0.0
  - pip:
    - deepface
    - pyniryo2
    - pyniryo
    - ultralytics
    - dlib
